site_name: Mural documentation
site_url: http://mural.monomelodies.nl/docs/
repo_url: https://github.com/monomelodies/mural

pages:
- Home:
    - 'Quickstart': 'index.md'

copyright: Copyright &copy; 2015, <a href="http://www.monomelodies.nl/">Marijn Ophorst</a>

